Задача 1. Инициализация рабочего окружения
ArtemKhel/formal-lang-course pull request #1
Opened 2023-09-10 16:53 UTC by ArtemKhel

# Задача 1. Инициализация рабочего окружения

* **Мягкий дедлайн**: 11.09.2023, 23:59
* **Жёсткий дедлайн**: 14.09.2023, 23:59
* Полный балл: 5

## Задача

- [x] Сделать `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1-vx82auNr0PQDQ3SwA7IYewZyOC9iHIaoX1w1qRUZ3I/edit?usp=sharing).
- [ ] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1-vx82auNr0PQDQ3SwA7IYewZyOC9iHIaoX1w1qRUZ3I/edit?usp=sharing))
- [x] Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
  - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#get-a-real-graph).
  - [x] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.

2023-09-13 18:56 UTC, Pogozhelskaya requested changes

2023-09-13 18:56 UTC, Pogozhelskaya commented on .github/workflows/code_style.yml
>      runs-on: ubuntu-latest
+ Windows 
+ MacOS

2023-09-13 18:56 UTC, Pogozhelskaya commented on .github/workflows/code_style.yml
> +#          pre-commit run --all-files --color always --verbose --show-diff-on-failure
?

2023-09-13 18:56 UTC, Pogozhelskaya commented on .github/workflows/tests.yml
> +    runs-on: ubuntu-latest
То же самое

2023-09-13 18:56 UTC, Pogozhelskaya commented on project/__init__.py
?

2023-09-13 18:56 UTC, Pogozhelskaya commented on project/utils/graphs.py
> +from networkx import MultiDiGraph
Для чего дублировать импорты?

2023-09-13 18:56 UTC, Pogozhelskaya commented on project/utils/graphs.py
> +def load_graph(name: str) -> MultiDiGraph:
```suggestion
def load_graph(name: str) -> nx.MultiDiGraph:
```

2023-09-13 19:52 UTC, Pogozhelskaya commented on project/utils/graphs.py
> +    nx.drawing.nx_pydot.to_pydot(graph).write(path)
https://github.com/networkx/networkx/issues/5723

2023-09-13 22:47 UTC, ArtemKhel commented on .github/workflows/code_style.yml
>      runs-on: ubuntu-latest
Добавил

2023-09-13 22:48 UTC, ArtemKhel commented on .github/workflows/code_style.yml
> +#          pre-commit run --all-files --color always --verbose --show-diff-on-failure
Убрал

2023-09-13 22:48 UTC, ArtemKhel commented on project/utils/graphs.py
> +from networkx import MultiDiGraph
Почистил импорты

2023-09-13 22:54 UTC, ArtemKhel commented on project/utils/graphs.py
> +    nx.drawing.nx_pydot.to_pydot(graph).write(path)
networkx идет зависимостью от cfpq-data и жестко [привязан](https://github.com/FormalLanguageConstrainedPathQuerying/CFPQ_Data/blob/2f5668bd22eeaa0e6931307cd4efd7ce53b80384/requirements/default.txt#L1) на версию 2.6.2 2-х летней давности, так что issue, можно сказать, из будущего 🙃. Стоит ли тащить зависимость ради 1 простой функции?

2023-09-14 14:10 UTC, Pogozhelskaya approved these changes

2023-09-14 14:30 UTC, merged